change range of rdf:predicate + small HTML fixes
w3c/rdf-schema pull request #8
Opened 2023-02-16 10:02 UTC by domel

see
https://www.w3.org/2001/sw/wiki/RDF1.1_Errata#erratum_31 
https://lists.w3.org/Archives/Public/public-rdf-comments/2021Dec/0000.html 
https://lists.w3.org/Archives/Public/public-rdf-comments/2021Dec/0002.html

2023-02-16 10:34 UTC, pfps commented
Why is the change being made to the range instead of to the wording when the summary persuasively argues that the change should be made to the wording?

2023-03-30 16:45 UTC, TallTed commented
@pfps — Could you suggest the edit you would make, as suggested revision(s) (a/k/a requested change(s)) of this PR?

2023-03-30 18:00 UTC, pfps commented
There are two parts to this PR.  One part is strictly editorial and could be separated out into its own PR.   The other is a change to the rdfs:range of rdf:predicate from rdfs:Resource to rdfs:Property.   The rest of the section on rdf:predicate reads as if the values of this property are of necessity instances of rdf:Property (not rdfs:Property as in the PR).  

The question is what change is to be made, if any.   Part of the contents of www.w3.org/1999/02/22-rdf-syntax-ns are also relevant to the change, namely

```
rdf:predicate a rdf:Property ;
	rdfs:isDefinedBy <http://www.w3.org/1999/02/22-rdf-syntax-ns#> ;
	rdfs:label "predicate" ;
	rdfs:comment "The predicate of the subject RDF statement." ;
	rdfs:domain rdf:Statement ;
	rdfs:range rdfs:Resource .
```

https://www.w3.org/2001/sw/wiki/RDF1.1_Errata#erratum_31 lists this as an editorial change which is not the case for the change suggested in https://lists.w3.org/Archives/Public/public-rdf-comments/2021Dec/0000.html and in this PR.   A change that is more along the lines of an editorial change would be to replace `states that S is an instance of rdf:Statement, that P is an instance of rdf:Property and that the predicate of S is P.` with `states that S is an instance of rdf:Statement and that the predicate of S is P.`, i.e., removing the wording implying that values of rdf:predicate are of necessity instances of rdf:Property.   If this is the change that is made there probably should be an explanation something like the following:

`
Instances of rdfs:Statement are not triples in an RDF graph so their values for rdf:predicate do not need to be instances of rdf:Property in that graph, although in most cases they will be.
`

2023-04-04 16:59 UTC, pchampin requested changes

2023-04-04 16:59 UTC, pchampin commented on spec/index.html
> +        and the <a href="#ch_range"><code>rdfs:range</code></a> is <a href="#ch_resource"><code>rdfs:Property</code></a>.</p>
```suggestion
        and the <a href="#ch_range"><code>rdfs:range</code></a> is <a href="#ch_resource"><code>rdfs:Resource</code></a>.</p>
```

My take away from the email discussion was that the range of rdf:predicate (`rdf:Resource`) was in fact correct, and that the misleading sentence "states that S is..." that seemed to imply a different range (`rdf:Property`) was to be fixed by removing "that P is an instance of `rdf:Property`".

See https://lists.w3.org/Archives/Public/public-rdf-comments/2021Dec/0005.html (last email of the thread).

With the propose (un)change above, this PR is limited to its "small HTML fixes", and is therefore purely editorial.

2023-04-12 16:32 UTC, pfps commented
The wording, "states that S is an instance of[ rdf:Statement ](https://pr-preview.s3.amazonaws.com/w3c/rdf-schema/8/e3fc106...bb0603b.html#ch_statement), that P is an instance of[ rdf:Property ](https://pr-preview.s3.amazonaws.com/w3c/rdf-schema/8/e3fc106...bb0603b.html#ch_property)and that the predicate of S is P." that initially caused the bug report is not being changed by the current PR but should be.

2023-04-13 16:33 UTC, pfps commented
Right now this PR only has two simple HTML changes, nothing about the range of rdf:predicate.  I'm going to change the name of the PR.  I suggest that it then be merged in as a single commit (using the squash option).   I'll create a separate PR for the fixes for the erratum.

2023-04-13 16:41 UTC, pfps commented
@TallTed  I don't think that my suggestion should moot a description of how to suggest or request changes to a PR that go outside the lines showing up in the changed files page.

2023-04-13 20:50 UTC, pfps commented
@pchampin Could you check to see whether your requested changes have been satisfactorily addressed?

2023-04-14 16:54 UTC, TallTed commented
@pfps -- 

If I understand this correctly --

> @TallTed I don't think that my suggestion should moot a description of how to suggest or request changes to a PR that go outside the lines showing up in the changed files page.

-- I would suggest that you create a PR against [the fork behind this PR](https://github.com/w3c/rdf-schema/tree/predicate-range).

Assuming acceptance, your PR can be merged into [that fork](https://github.com/w3c/rdf-schema/tree/predicate-range), and then [this PR](https://github.com/w3c/rdf-schema/pull/8) can be merged into [main](https://github.com/w3c/rdf-schema).

2023-04-17 23:02 UTC, TallTed commented
@pfps — Ah, you're one of those CLI `git` users. 

As a browser-interface user, I have never cloned the repo myself (though GitHub has done so for me). I would go to https://github.com/w3c/rdf-schema/tree/predicate-range; drill to the file I want to edit (appears likely to be `spec/index.html`); click the pencil icon (upper-right of the source pane within the browser tab); make my desired edits to the body; scroll to the bottom and make decisions about a new fork (for a pull request) or a direct merge (for no pull request), add a short description of my edits, and the like; then click "make pull request" on the next page.  Most of this is follow-your-nose kind of stuff, though it can be confusingly simple for people used to `git` CLI and confusingly complex for people not used to source control.

Perhaps that gets you somewhere?

2023-04-20 16:23 UTC, pfps commented
@pchampin It appears that you are blocking this PR

2023-04-20 16:53 UTC, domel commented
Now this PR to not change anything. Can I close it?

2023-04-20 18:20 UTC, pfps commented
The PR still adds some HTML markup, so it's not doing nothing.

2023-04-20 19:10 UTC, domel commented
@pfps I double check and there is no markup edits. In addition, I know my commit so that there is nothing there. 🙂 What you see is generated automatically by respec.

2023-04-20 19:11 UTC, pfps commented
I click on Files changed and I see two changes.

2023-04-21 17:56 UTC, TallTed commented
@pchampin — I see two HTML changes, wrapping two strings (`rdf:predicate` and `rdf:object`) in `<code>` tags. I think these changes are worthwhile, and could be considered "small HTML fixes". Would you please approve this PR, such that hopefully @pfps can merge it?

2023-04-27 17:09 UTC, pchampin approved these changes
sorry for not being reactive

2023-04-27 18:06 UTC, merged